-- MySQL Script generated by MySQL Workbench
-- vie 10 jun 2022 16:06:59
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema productos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema productos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `productos` ;
USE `productos` ;

-- -----------------------------------------------------
-- Table `productos`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `productos`.`producto` (
  `codigo` INT NOT NULL,
  `descripcion` VARCHAR(200) NULL,
  `marca` VARCHAR(45) NULL,
  `cantidad` INT NOT NULL DEFAULT 0,
  `precioUnitario` FLOAT NOT NULL DEFAULT 0,
  `iva` FLOAT NOT NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
